# +--------------------------------------------------------------+
# |                                                              |
# |         Welcome to ItemManager config!                         |
# |                                                              |
# +--------------------------------------------------------------+

#Maker Setting
Maker:
  #Register your own Register details using the anchor. Use Elias for the items.
  CustomSetting:
  GlobalSetting:
    Admin:
      Provide: true
      Permission: item-manager.make.admin
      Setting:
        AllowOverEnchanting: true
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: true
    Citizen:
      Provide: false
      Permission: item-manager.make.everyone
      Setting:
        AllowOverEnchanting: false
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: false

#Recorder Setting
Recorder:
  CustomSetting:
  GlobalSetting:
    Admin:
      Provide: true
      Permission:
        Register: item-manager.record.Register.admin
        Edit: item-manager.record.edit.admin
        Delete: item-manager.record.delete.admin
    Citizen:
      Provide: false
      Permission:
        Register: item-manager.record.Register.everyone
        Edit: item-manager.record.edit.everyone
        Delete: item-manager.record.delete.everyone

#Editor Setting
Editor:
  CustomSetting:
  GlobalSetting:
    Admin:
      Provide: true
      Permission: item-manager.edit.admin
      Setting:
        AllowOverEnchanting: true
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: false
    Citizen:
      Provide: false
      Permission: item-manager.edit.everyone
      Setting:
        AllowOverEnchanting: false
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: false