# +--------------------------------------------------------------+
# |                                                              |
# |         Welcome to ItemManager config!                         |
# |                                                              |
# +--------------------------------------------------------------+

#Maker Setting
Maker:
  #Register your own Register details using the anchor. Use Elias for the items.
  CustomSetting:
  GlobalSetting:
    Admin:
      Provide: true
      Permission:
        All: item-manager.maker.admin
        Basic: item-manager.maker.basic.admin
        Attribute: item-manager.maker.attribute.admin
        Enchanting: item-manager.maker.enchanting.admin
        ItemFlag: item-manager.maker.item-flag.admin
        Lore: item-manager.maker.lore.admin
        ColorName: item-manager.maker.name-color.admin
        AdminItems: item-manager.maker.admin-items.admin
      Setting:
        AllowOverEnchanting: true
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: true
    Citizen:
      Provide: false
      Permission:
        All: item-manager.maker.everyone
        Basic: item-manager.maker.basic.everyone
        Attribute: item-manager.maker.attribute.everyone
        Enchanting: item-manager.maker.enchanting.everyone
        ItemFlag: item-manager.maker.item-flag.everyone
        Lore: item-manager.maker.lore.everyone
        ColorName: item-manager.maker.name-color.everyone
        AdminItems: item-manager.maker.admin-items.everyone
      Setting:
        AllowOverEnchanting: false
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: false

#Recorder Setting
Recorder:
  CustomSetting:
  GlobalSetting:
    Admin:
      Provide: true
      Permission:
        Register: item-manager.record.Register.admin
        Edit: item-manager.record.edit.admin
        Delete: item-manager.record.delete.admin
    Citizen:
      Provide: false
      Permission:
        Register: item-manager.record.Register.everyone
        Edit: item-manager.record.edit.everyone
        Delete: item-manager.record.delete.everyone

#Editor Setting
Editor:
  CustomSetting:
  GlobalSetting:
    Admin:
      Provide: true
      Permission:
        All: item-manager.edit.admin
        Attribute: item-manager.edit.attribute.admin
        Basic: item-manager.edit.basic.admin
        Enchanting: item-manager.edit.enchanting.admin
        ItemFlag: item-manager.edit.item-flag.admin
        Lore: item-manager.edit.lore.admin
        ColorName: item-manager.edit.name-color.admin
      Setting:
        AllowOverEnchanting: true
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: false
    Citizen:
      Provide: false
      Permission:
        All: item-manager.edit.everyone
        Attribute: item-manager.edit.attribute.everyone
        Basic: item-manager.edit.basic.everyone
        Enchanting: item-manager.edit.enchanting.everyone
        ItemFlag: item-manager.edit.item-flag.everyone
        Lore: item-manager.edit.lore.everyone
        ColorName: item-manager.edit.name-color.everyone
      Setting:
        AllowOverEnchanting: false
        AllowCustomEnchantments:
          Allow: false
          Plugin: null
        AutoRecord: false